import {Colors} from 'Theme';

const utils = {
  // states: [
  //   {
  //     stage: 1,
  //     state: 'Pending',
  //     title: 'Pending',
  //     subTitle: ' to accept your order',
  //     image: require('@Images/pending.gif'),
  //     color: Colors.primary,
  //   },
  //   {
  //     stage: 2,
  //     state: 'Vendor Confirmed',
  //     title: 'Preparing your food',
  //     subTitle: ' has accepted your order and is being prepared',
  //     color: Colors.primary,
  //     image: require('@Images/cooking.gif'),
  //   },
  //   {
  //     stage: 2,
  //     state: 'Ready For Delivery',
  //     title: 'Preparing your food',
  //     subTitle: ' has accepted your order and is being prepared',
  //     color: Colors.primary,
  //     image: require('@Images/cooking.gif'),
  //   },
  //   {
  //     stage: 2,
  //     state: 'Delivery Confirmed',
  //     title: 'Preparing your food',
  //     subTitle: ' has accepted your order and is being prepared',
  //     color: Colors.primary,
  //     image: require('@Images/cooking.gif'),
  //   },
  //   {
  //     stage: 2,
  //     state: 'Driver Enroute',
  //     title: 'Preparing your food',
  //     subTitle: ' has accepted your order and is being prepared',
  //     color: Colors.primary,
  //     image: require('@Images/cooking.gif'),
  //   },
  //   {
  //     stage: 3,
  //     state: 'Driver Arrived',
  //     title: 'Locating driver',
  //     subTitle: 'We are locating driver for you',
  //     color: Colors.primary,
  //     image: require('@Images/finding_driver.gif'),
  //   },
  //   {
  //     stage: 4,
  //     state: 'Driver POB',
  //     title: 'Driver Enroute',
  //     subTitle: 'Your Order is on the way',
  //     color: Colors.primary,
  //     image: require('@Images/driver_enroute.gif'),
  //   },
  //   {
  //     stage: 5,
  //     state: 'Completed',
  //     title: 'Completed',
  //     subTitle: 'Your Order has been Delivered',
  //     color: '#46CF99',
  //     image: require('@Images/completed.gif'),
  //   },
  //   {
  //     stage: 0,
  //     state: 'Timed Out',
  //     title: 'Timed Out',
  //     subTitle: ' was unable to fulfill your Order',
  //     color: Colors.error,
  //     image: require('@Images/timed_out.gif'),
  //   },
  //   {
  //     stage: 0,
  //     state: 'Vendor Cancelled',
  //     title: 'Vendor Cancelled',
  //     subTitle: ' was unable to fulfill your Order',
  //     color: Colors.error,
  //     image: require('@Images/timed_out.gif'),
  //   },
  //   {
  //     stage: 0,
  //     state: 'Delivery Cancelled',
  //     title: 'Delivery Cancelled',
  //     subTitle: ' was unable to fulfill your Order',
  //     color: Colors.error,
  //     image: require('@Images/timed_out.gif'),
  //   },
  // ],
};

export default utils;
